### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by nelia89** [bio15anu/revelio#2]
Hi, thank you so much for sharing this tool. I am very interested in using your script to get a masked.bam file to use it for subsequent variant calling analysis. 

I already try the two different commands.

I obtained the calmd.bam output file when I run the samtools calmd -b command, but I did not obtain the masked.bam file. 

And when I runned : ./revelio.py -f genome.fa input.bam masked.bam

I obtained this error:

Traceback (most recent call last):
  File "./revelio.py", line 445, in <module>
    main(args.inbam,args.outbam,args.QUALITY,args.THREADS,args.temp,args.fasta)
  File "./revelio.py", line 94, in main
    header = original.header.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'

Many thanks in advance for your help

**Comment by bio15anu** [comment]
Very sorry for the very late reply @nelia89, I somehow missed this issue! I hope you were able to solve it by yourself? It seems to me that you have not installed software dependencies prior to running Revelio, as [`to_dict()`](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentHeader.to_dict) is a method from the pysam library. The error is stating that it does not recognise the method, which indicates that the library has not been loaded.

Please refer to the instructions on the [landing page on Github](https://github.com/bio15anu/revelio) for installing pysam with conda.
